### ISSUE TITLE
Crash when opening images

### ISSUE THREAD

**Issue by lionep** [pipiliang/docker-dashboard#10]
App is crashing when clicking on "Images", on ubuntu server 16.04

```
$ docker-dashboard 
TypeError: Cannot read property '0' of null
    at images.forEach.s (/usr/lib/node_modules/docker-dashboard/lib/widget-images.js:26:23)
    at Array.forEach (native)
    at Object.self.docker.listImages [as callback] (/usr/lib/node_modules/docker-dashboard/lib/widget-images.js:23:10)
    at /usr/lib/node_modules/docker-dashboard/node_modules/dockerode/lib/docker.js:460:12
    at Modem.buildPayload (/usr/lib/node_modules/docker-dashboard/node_modules/docker-modem/lib/modem.js:259:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/docker-dashboard/node_modules/docker-modem/lib/modem.js:218:14)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
```

**Comment by itwars** [comment]
Same for me!

**Comment by pipiliang** [comment]
eric-hansen fix this issue， we will publish it to the next version， thanks！
