### ISSUE TITLE
Crash on mac

### ISSUE THREAD

**Issue by lionep** [pipiliang/docker-dashboard#11]
Happens with node v6.9.1, directly on launch
```
TypeError: text.replace is not a function
    at Object.helpers.stripTags (/Users/lionel/.nvm/versions/node/v6.9.4/lib/node_modules/docker-dashboard/node_modules/blessed/lib/helpers.js:137:6)
    at ScrollableBox.Element.strWidth (/Users/lionel/.nvm/versions/node/v6.9.4/lib/node_modules/docker-dashboard/node_modules/blessed/lib/widgets/element.js:2543:15)
    at /Users/lionel/.nvm/versions/node/v6.9.4/lib/node_modules/docker-dashboard/node_modules/blessed/lib/widgets/table.js:71:23
    at Array.forEach (native)
    at /Users/lionel/.nvm/versions/node/v6.9.4/lib/node_modules/docker-dashboard/node_modules/blessed/lib/widgets/table.js:70:9
    at Array.forEach (native)
    at ScrollableBox.Table._calculateMaxes (/Users/lionel/.nvm/versions/node/v6.9.4/lib/node_modules/docker-dashboard/node_modules/blessed/lib/widgets/table.js:69:13)
    at ScrollableBox.ListTable.render (/Users/lionel/.nvm/versions/node/v6.9.4/lib/node_modules/docker-dashboard/node_modules/blessed/lib/widgets/listtable.js:171:8)
    at /Users/lionel/.nvm/versions/node/v6.9.4/lib/node_modules/docker-dashboard/node_modules/blessed/lib/widgets/element.js:2334:8
    at Array.forEach (native)
```

**Comment by Iliyass** [comment]
I have issue here on 
- macOS 10.12.5
- node v6.10.0
- npm v3.10.10

**Comment by rvion** [comment]
same here:
```
TypeError: text.replace is not a function
    at Object.helpers.stripTags (/usr/local/lib/node_modules/docker-dashboard/node_modules/blessed/lib/helpers.js:137:6)
    at ScrollableBox.Element.strWidth (/usr/local/lib/node_modules/docker-dashboard/node_modules/blessed/lib/widgets/element.js:2543:15)
    at /usr/local/lib/node_modules/docker-dashboard/node_modules/blessed/lib/widgets/table.js:71:23
    at Array.forEach (native)
    at /usr/local/lib/node_modules/docker-dashboard/node_modules/blessed/lib/widgets/table.js:70:9
    at Array.forEach (native)
    at ScrollableBox.Table._calculateMaxes (/usr/local/lib/node_modules/docker-dashboard/node_modules/blessed/lib/widgets/table.js:69:13)
    at ScrollableBox.ListTable.render (/usr/local/lib/node_modules/docker-dashboard/node_modules/blessed/lib/widgets/listtable.js:171:8)
    at /usr/local/lib/node_modules/docker-dashboard/node_modules/blessed/lib/widgets/element.js:2334:8
    at Array.forEach (native)
```

**Comment by nickelzhang** [comment]
/usr/local/lib/node_modules/docker-dashboard/node_modules/blessed/lib/helpers.js
:
136行
helpers.stripTags = function(text) {
  text = text + "";
  if (!text) return '';
  return text
    .replace(/{(\/?)([\w\-,;!#]*)}/g, '')
    .replace(/\x1b\[[\d;]*m/g, '');
};

**Comment by pipiliang** [comment]
Thanks for the feedback, please update to the latest version 0.1.6.
