### ISSUE TITLE
crash on RHEL7

### ISSUE THREAD

**Issue by magixyu** [pipiliang/docker-dashboard#14]
[root@ding ~]# docker-dashboard
TypeError: value.toFixed is not a function
    at formatYLabel (/usr/lib/node_modules/docker-dashboard/node_modules/blessed-contrib/lib/widget/charts/line.js:114:23)
    at getMaxXLabelPadding (/usr/lib/node_modules/docker-dashboard/node_modules/blessed-contrib/lib/widget/charts/line.js:121:14)
    at Line.setData (/usr/lib/node_modules/docker-dashboard/node_modules/blessed-contrib/lib/widget/charts/line.js:124:22)
    at refreshData (/usr/lib/node_modules/docker-dashboard/lib/widget-container.js:86:11)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/docker-dashboard/lib/widget-container.js:138:6)
    at emitOne (events.js:116:13)
    at IncomingMessage.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at IncomingMessage.Readable.push (_stream_readable.js:208:10)

**Comment by magixyu** [comment]
[root@ding ~]# docker version
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:09:15 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:13:03 2018
  OS/Arch:      linux/amd64
  Experimental: false

**Comment by hexmind** [comment]
```
TypeError: value.toFixed is not a function
    at formatYLabel (/usr/local/lib/node_modules/docker-dashboard/node_modules/blessed-contrib/lib/widget/charts/line.js:114:23)
    at getMaxXLabelPadding (/usr/local/lib/node_modules/docker-dashboard/node_modules/blessed-contrib/lib/widget/charts/line.js:121:14)
    at Line.setData (/usr/local/lib/node_modules/docker-dashboard/node_modules/blessed-contrib/lib/widget/charts/line.js:124:22)
    at refreshData (/usr/local/lib/node_modules/docker-dashboard/lib/widget-container.js:86:11)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/docker-dashboard/lib/widget-container.js:138:6)
    at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at IncomingMessage.Readable.push (_stream_readable.js:110:10)
    at HTTPParser.parserOnBody (_http_common.js:109:22)
```
```
$ docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false

```

**Comment by pipiliang** [comment]
Thanks for the feedback, please update to the latest version 0.1.6.
